name: 'Deploy Backend Application'
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload build artifact
        run: actions/upload-artifact@v4
        with: 
          name: artifact
          path: |
            api/*
            !api/src
            !api/test
            !api/node_modules
  deploy-dev:
    name: Deploy dev-environment
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download build artifacts
        uses: artifact/download-artifact@v4
        with: 
          name: artifact
          path: artifact
      - name: Zip artifact for Deployment
        runs: |
          cd artifact
          zip -r ../service.zip ./*
      - name: Deploy to EB
        uses: sdfsdfsdfsdf #Editar aqui
        with: 
          aws_access_key: 1234586 # Editar
          aws_secret_key: 1234596 # Editar
          application_name: Application_name # Editar
          environment_name: developmento # Talvez editar aqui
          region: us-east-1
          version_label: ${{ github.run_id }}
          deployment_package: service.zip
          use_existing_version_if_available: true